### ISSUE TITLE
When exporting the excel file all the cells are empty

### ISSUE THREAD

**Issue by uialberto** [fingers10/ExcelExport#5]
When exporting the excel file all the cells are empty, the file has no data

**Comment by uialberto** [comment]
My project is net core 3.1

![image](https://user-images.githubusercontent.com/854471/84667770-c9d84780-aef0-11ea-8070-e78f826be627.png)
![image](https://user-images.githubusercontent.com/854471/84667785-d0ff5580-aef0-11ea-9266-e1a8e3e442fb.png)

**Comment by fingers10** [comment]
Are you sure you followed the docs and added the required attributes in your model?

**Comment by uialberto** [comment]
Yes, you can review this test project where I am using the Fingers10 ExcelExport library.

https://github.com/uialberto/coredatable

**Comment by uialberto** [comment]
Thank you. My mistake was in the excel report attributes. :)
